apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

nameSuffix: -dev

commonLabels:
  environment: dev

replicas:
  - name: vote
    count: 1
  - name: result
    count: 1

images:
  - name: anik1999/vote-app
    newTag: "latest"
  - name: anik1999/result-app
    newTag: "latest"		
