apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

nameSuffix: -prod

commonLabels:
  environment: prod

replicas:
  - name: vote
    count: 1
  - name: result
    count: 1

images:
  - name: anik1999/vote-app
    newTag: "49de728b3d16c9c3552742fe4c6e147095c695d2"
  - name: anik1999/result-app
    newTag: "49de728b3d16c9c3552742fe4c6e147095c695d2"
